// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpDelivery.Logistics.Infrastructure.Data;

#nullable disable

namespace UpDelivery.Logistics.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424083509_UpdateLogisticsSchema")]
    partial class UpdateLogisticsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.DeliveryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LogisticsOrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsOrderId");

                    b.HasIndex("RiderId");

                    b.ToTable("DeliveryAssignments");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.DeliveryStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogisticsOrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OldStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsOrderId");

                    b.ToTable("DeliveryStatusHistories");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.DeliveryTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Heading")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogisticsOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpeedKmh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsOrderId");

                    b.HasIndex("RiderId");

                    b.ToTable("DeliveryTrackings");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.FailedDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogisticsOrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsOrderId")
                        .IsUnique();

                    b.ToTable("FailedDeliveries");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.LogisticsOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChefreshOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryLatitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryLongitude")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeliveryWindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryWindowStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PickupLatitude")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PickupLongitude")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogisticsOrders");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.ProofOfDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DeliveredByRiderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogisticsOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogisticsOrderId")
                        .IsUnique();

                    b.ToTable("ProofsOfDelivery");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.Rider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxLoadKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Riders");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapacityKg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RiderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RiderId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.DeliveryAssignment", b =>
                {
                    b.HasOne("UpDelivery.Logistics.Core.Entities.LogisticsOrder", "LogisticsOrder")
                        .WithMany("Assignments")
                        .HasForeignKey("LogisticsOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpDelivery.Logistics.Core.Entities.Rider", "Rider")
                        .WithMany("Assignments")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticsOrder");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.DeliveryStatusHistory", b =>
                {
                    b.HasOne("UpDelivery.Logistics.Core.Entities.LogisticsOrder", "LogisticsOrder")
                        .WithMany("StatusHistories")
                        .HasForeignKey("LogisticsOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticsOrder");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.DeliveryTracking", b =>
                {
                    b.HasOne("UpDelivery.Logistics.Core.Entities.LogisticsOrder", "LogisticsOrder")
                        .WithMany("Trackings")
                        .HasForeignKey("LogisticsOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpDelivery.Logistics.Core.Entities.Rider", "Rider")
                        .WithMany("Trackings")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticsOrder");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.FailedDelivery", b =>
                {
                    b.HasOne("UpDelivery.Logistics.Core.Entities.LogisticsOrder", "LogisticsOrder")
                        .WithOne("FailedDelivery")
                        .HasForeignKey("UpDelivery.Logistics.Core.Entities.FailedDelivery", "LogisticsOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticsOrder");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.ProofOfDelivery", b =>
                {
                    b.HasOne("UpDelivery.Logistics.Core.Entities.LogisticsOrder", "LogisticsOrder")
                        .WithOne("ProofOfDelivery")
                        .HasForeignKey("UpDelivery.Logistics.Core.Entities.ProofOfDelivery", "LogisticsOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticsOrder");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("UpDelivery.Logistics.Core.Entities.Rider", "Rider")
                        .WithMany("Vehicles")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.LogisticsOrder", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("FailedDelivery");

                    b.Navigation("ProofOfDelivery");

                    b.Navigation("StatusHistories");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("UpDelivery.Logistics.Core.Entities.Rider", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Trackings");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
